### PR TITLE
Spanish Update

### PR DESCRIPTION
**Pull request by Juessa**
The above Spanish translation was in Portuguese. I am Mexican, I will help in Spanish translations .

### CODE REVIEW

**Comment by Plazmaz** [comment]
It wasn't Portuguese, just my awful Spanish :laughing:
Thank you for your contribution.

**Comment by Plazmaz** [comment]
Interesting. Is "Tú esta no estas" a mistake? It seems redundant.

**Comment by Juessa** [comment]
O, yes, i'm sorry haha,it was a mistake.

**Comment by Plazmaz** [comment]
Update it and you should be all good.

**Comment by Juessa** [comment]
I think that's all

**Comment by Juessa** [comment]
I hope I've helped

**Comment by Plazmaz** [comment]
Absolutely! Thanks :smile:

**Comment by Juessa** [comment]
Thanks!, If you need help on something else, do not hesitate to ask me.

**Pull request merged**
