### PR TITLE
sk_sk.json

### PR DESCRIPTION
**Pull request by MrHedryX**
Translated from Czech language, because our languages are very similar. I hope i helped you :) Thank to you for giving us 
possibility to translate your plugin. Have a nice day :)                              
                                                                                                                               -MrHedryX

### CODE REVIEW

**Comment by lenis0012** [comment]
@MrHedryX Could you change the name to sk_sk.json?

**Comment by MrHedryX** [comment]
Done :)

**Comment by lenis0012** [comment]
Thank you very much @MrHedryX for your contribution.

**Comment by MrHedryX** [comment]
NP :)

**Pull request merged**
