### PR TITLE
Translated to Japanese

### PR DESCRIPTION
**Pull request by raspi0124**

### CODE REVIEW

**Comment by Plazmaz** [comment]
Thank you for your contribution, however, all files must be .json files. Please resolve this before I merge.

**Comment by lenis0012** [comment]
@raspi0124 aka, rename your file to jp_jp.json =)

**Comment by raspi0124** [comment]
I think it's good now.

**Comment by Plazmaz** [comment]
Looks good, I will merge when I'm home if @lenis0012 doesn't beat me to it.

**Pull request merged**
