### PR TITLE
Added more Languages

### PR DESCRIPTION
**Pull request by Tzzzt123**

### CODE REVIEW

**Comment by Tzzzt123** [comment]
@lenis0012 please read

**Comment by Vilican** [comment]
@Tzzzt123 - Correct is "Czech Republic" instead of "Czech Repuplic".

**Comment by Vilican** [comment]
And it is not `cz_cz.json`, it is `cs_cz.json`. Please be more careful when you write.

**Comment by Tzzzt123** [comment]
sorry @Vilican

**Comment by Tzzzt123** [comment]
@lenis0012 please read

**Pull request merged**
