### PR TITLE
Latin translation!

### PR DESCRIPTION
**Pull request by Tzzzt123**
2 infos:
i do have latin at school
and it may have some errors

### CODE REVIEW

**Comment by Tzzzt123** [comment]
@lenis0012 @plazmaz please merge

**Comment by Plazmaz** [comment]
Should just be "Latina", no?

**Comment by Tzzzt123** [comment]
Lingva Latina means the latin language
but latina is an adjective for saying latin
@Plazmaz

**Comment by Plazmaz** [comment]
Ah okay, that works

**Pull request merged**
