### PR TITLE
Create id_id.json

### PR DESCRIPTION
**Pull request by taeyeonviernes**
This is a translation of Indonesian. I'm sure it's pretty accurate and very easy to understand these words. Hope this translation helps this plugin to be better. Thank you!

### CODE REVIEW

**Comment by Tzzzt123** [comment]
Ok, looks good, @Plazmaz and @lenis0012 merge it please.
Imma update the readme.MD file when merged.

**Comment by Plazmaz** [comment]
Please update the author name to your alias.

**Comment by taeyeonviernes** [comment]
Okay..

**Comment by Plazmaz** [comment]
Looks good!

**Comment by taeyeonviernes** [comment]
Thanks! :)

**Pull request merged**
