### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by Furestry**
Changed "pluginVersion": "3.0.0" to "pluginVersion": "3.0.2"
add translate for "kickUsernameRegistered": "This account is registered under the name %username%, please log in as such.",
and fixed misstake in 4d line: "authors": "Scurovoid","Sevler" to "authors": "Scurovoid,Sevler",

### CODE REVIEW

**Comment by lenis0012** [comment]
Thanks for fixing it, I didn't even notice.
Normally github marks json syntax erors in red.

It will be in 3.0.2, but you can also grab the new version at https://ci.codemc.io/job/lenis0012/job/LoginSecurity/58/

**Comment by Furestry** [comment]
Ok thanks and again I'm sorry for the mistake, this translation is my first work on github

**Comment by lenis0012** [comment]
@Furestry No problem, it happens, I should have seen the issue to be honest haha.
Thanks for the work :)

**Comment by Furestry** [comment]
@lenis0012 The question is not in that place, but I saw that you can do offline translation, but how? Just add the json file with the translation to the config folder?

**Comment by Furestry** [comment]
@GhostRecon312 в 3.0.2 вообще не работает из-за моего косяка) в 3.0.3 да, так же, даже не знаю почему

**Pull request merged**
